# Generated by Django 5.1.5 on 2025-02-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nacimiento', models.IntegerField(blank=True, null=True)),
                ('fallecimiento', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto_gutenberg', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=500)),
                ('temas', models.JSONField()),
                ('idiomas', models.JSONField()),
                ('cantidad_descargas', models.IntegerField()),
                ('enlace', models.URLField()),
                ('primer_parrafo_en', models.TextField(blank=True, null=True)),
                ('primer_parrafo_es', models.TextField(blank=True, null=True)),
                ('autores', models.ManyToManyField(related_name='libros', to='api.autor')),
            ],
        ),
    ]
