# Generated by Django 5.1.5 on 2025-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_libro_titulo_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='pista_IA',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_IA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
